# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18kj_UqDGfYanNaccDNFdJM6iBm-pBmb0
"""

!pip install pandas matplotlib seaborn scikit-learn

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

# Sample data
data = {
    'Country': ['USA', 'UK', 'Germany', 'France', 'China', 'India', 'Australia', 'Brazil'],
    'Tourists (millions)': [80, 39, 38, 89, 65, 17, 9, 6],
    'Avg Spend ($)': [1200, 1100, 1150, 1050, 980, 870, 920, 800],
    'Stay Duration (days)': [8, 7, 9, 7, 10, 12, 10, 11]
}
df = pd.DataFrame(data)
df

# Drop non-numeric column for clustering
features = df.drop('Country', axis=1)

# Standardize features
scaler = StandardScaler()
scaled = scaler.fit_transform(features)

kmeans = KMeans(n_clusters=3, random_state=42)
df['Cluster'] = kmeans.fit_predict(scaled)
df

sns.pairplot(df, hue='Cluster', vars=['Tourists (millions)', 'Avg Spend ($)', 'Stay Duration (days)'])
plt.suptitle('Tourism Clusters Analysis', y=1.02)
plt.show()

# Group and summarize by cluster
cluster_summary = df.groupby('Cluster').mean(numeric_only=True)
cluster_summary